"""initial local schema

The client plane's tables: one user's collection and decks, on their own
machine. Applied by the backend container's ENTRYPOINT on start.

This is a fresh lineage. The pre-split history (d152d73339b7 and its two
descendants) created all six tables in one database and could not be split
into two chains, so it was squashed rather than carried forward -- nothing was
deployed anywhere for it to be compatible with.

Note what is *absent*: no foreign key from collection.card_id,
decks.commander_id or deck_cards.card_id to cards.oracle_id. Those are logical
references into a different database (docs/data-model.md), and nothing but
application code will ever enforce them.

Revision ID: 144381aa92d6
Revises: 
Create Date: 2026-09-20 07:27:33.005491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144381aa92d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    op.create_table('decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commander_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=False),
    sa.Column('proxy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_cards')
    op.drop_table('decks')
    op.drop_table('collection')
    # ### end Alembic commands ###
