"""add deck name/updated_at, deck_card quantity, card_metadata updated_at, nullable commander_id

Revision ID: 6499dc0149db
Revises: b8e5669ba97c
Create Date: 2026-09-15 21:28:53.716808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6499dc0149db'
down_revision: Union[str, Sequence[str], None] = 'b8e5669ba97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('commander_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.alter_column('commander_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('name')

    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('card_metadata', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
