"""add power, toughness, loyalty, defense to cards

Revision ID: b8e5669ba97c
Revises: d152d73339b7
Create Date: 2026-09-15 21:03:01.165357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e5669ba97c'
down_revision: Union[str, Sequence[str], None] = 'd152d73339b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('toughness', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('loyalty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('defense', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('defense')
        batch_op.drop_column('loyalty')
        batch_op.drop_column('toughness')
        batch_op.drop_column('power')

    # ### end Alembic commands ###
