"""initial schema

Revision ID: d152d73339b7
Revises: 
Create Date: 2026-08-17 13:22:35.368489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd152d73339b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('oracle_id', sa.String(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('mana_value', sa.Float(), nullable=False),
    sa.Column('oracle_text', sa.String(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('color_identity', sa.JSON(), nullable=False),
    sa.Column('type_line', sa.String(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('layout', sa.String(), nullable=False),
    sa.Column('legalities', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oracle_id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_name'), ['name'], unique=False)

    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bulk_type', sa.String(), nullable=False),
    sa.Column('format_profile', sa.String(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.Column('cards_seen', sa.Integer(), nullable=False),
    sa.Column('cards_written', sa.Integer(), nullable=False),
    sa.Column('cards_skipped', sa.Integer(), nullable=False),
    sa.Column('cards_pruned', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_metadata',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('game_stage', sa.String(), nullable=False),
    sa.Column('power_rating', sa.Float(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('synergy_tags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.oracle_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('collection',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.oracle_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    op.create_table('decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('commander_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['cards.oracle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=False),
    sa.Column('proxy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.oracle_id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_cards')
    op.drop_table('decks')
    op.drop_table('collection')
    op.drop_table('card_metadata')
    op.drop_table('import_runs')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_name'))

    op.drop_table('cards')
    # ### end Alembic commands ###
