"""initial knowledge schema

The knowledge plane's tables: the shared card corpus, its AI metadata, and the
importer's run log. Applied by maintainers against KNOWLEDGE_DATABASE_URL --
a run here is a publish, visible to every client at once.

This is a fresh lineage. The pre-split history (d152d73339b7 and its two
descendants) created all six tables in one database and could not be split
into two chains, so it was squashed rather than carried forward -- nothing was
deployed anywhere for it to be compatible with.

Revision ID: 586d2486ef8f
Revises: 
Create Date: 2026-09-20 07:27:22.332414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586d2486ef8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('oracle_id', sa.String(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('mana_value', sa.Float(), nullable=False),
    sa.Column('oracle_text', sa.String(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('color_identity', sa.JSON(), nullable=False),
    sa.Column('type_line', sa.String(), nullable=False),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('toughness', sa.String(), nullable=True),
    sa.Column('loyalty', sa.String(), nullable=True),
    sa.Column('defense', sa.String(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('layout', sa.String(), nullable=False),
    sa.Column('legalities', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oracle_id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_name'), ['name'], unique=False)

    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bulk_type', sa.String(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.Column('cards_seen', sa.Integer(), nullable=False),
    sa.Column('cards_written', sa.Integer(), nullable=False),
    sa.Column('cards_skipped', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_metadata',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('game_stage', sa.String(), nullable=False),
    sa.Column('power_rating', sa.Float(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('synergy_tags', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.oracle_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_metadata')
    op.drop_table('import_runs')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_name'))

    op.drop_table('cards')
    # ### end Alembic commands ###
